$gwx4_XC_1=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx4_XC_1 || [];
function gz$gwx4_XC_1_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx4_XC_1_1)return __WXML_GLOBAL__.ops_cached.$gwx4_XC_1_1
__WXML_GLOBAL__.ops_cached.$gwx4_XC_1_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'eventdetail data-v-73bbb264'])
Z([3,'__e'])
Z([3,'titlegroup data-v-73bbb264'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'close']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'title data-v-73bbb264'])
Z([3,'实名须知'])
Z([3,'data-v-73bbb264'])
Z([[6],[[7],[3,'$root']],[3,'m0']])
Z([3,'explain data-v-73bbb264'])
Z([3,'根据现行法律以及公安、防疫部门对大型活动实名制的要求，实名制的项目在购票时需要提供你的实名信息，并在接收方采取严格信息保护措施的前提下，并在接受方采取严格信息保护措施的前提下，用于出票、入场检验身份或防疫调查，实名信息包括姓名、身份证（或照/港澳居民来往内地通行证/台湾居民来往大陆通行证）。 为方便您迅速下单，您可选择在购票前添加并在购票过程中提交购票人实名信息。为保证信息的真实信息。为保证信息的真实性和唯一性，我们会基于您提供的信息通过征信平台或其他常规方式进行实名验证。'])
Z([3,'bottom data-v-73bbb264'])
Z(z[1])
Z([3,'save data-v-73bbb264'])
Z(z[3])
Z([3,'确定'])
})(__WXML_GLOBAL__.ops_cached.$gwx4_XC_1_1);return __WXML_GLOBAL__.ops_cached.$gwx4_XC_1_1
}
function gz$gwx4_XC_1_2(){
if( __WXML_GLOBAL__.ops_cached.$gwx4_XC_1_2)return __WXML_GLOBAL__.ops_cached.$gwx4_XC_1_2
__WXML_GLOBAL__.ops_cached.$gwx4_XC_1_2=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'data-v-bff0050c'])
Z([[2,'!='],[[7],[3,'platform']],[1,'TT']])
Z([3,'__l'])
Z(z[0])
Z([3,'看个比赛'])
Z([3,'9020c9ec-1'])
Z([3,'content data-v-bff0050c'])
Z([3,'bodyContent data-v-bff0050c'])
Z([[2,'+'],[[2,'+'],[1,'height:'],[[2,'?:'],[[7],[3,'activityCodeControl']],[[2,'+'],[1,990],[1,'rpx']],[[2,'+'],[1,860],[1,'rpx']]]],[1,';']])
Z(z[0])
Z([3,'display:flex;flex-direction:row;margin-top:70rpx;text-align:center;justify-content:center;margin-right:100rpx;'])
Z([3,'img-tip data-v-bff0050c'])
Z([[6],[[7],[3,'$root']],[3,'m0']])
Z([3,'b-title data-v-bff0050c'])
Z([3,'接收人'])
Z([3,'s-title data-v-bff0050c'])
Z([3,'填写以下信息即可接收成功'])
Z([3,'line data-v-bff0050c'])
Z([3,'margin-top:40rpx;'])
Z([3,'itembg data-v-bff0050c'])
Z([3,'xing data-v-bff0050c'])
Z([3,'*'])
Z([3,'lefttitle data-v-bff0050c'])
Z([3,'姓名'])
Z([3,'__e'])
Z([3,'inputPhone data-v-bff0050c'])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[1,'getInputValue']],[[4],[[5],[[5],[1,2]],[1,'$event']]]]]]]]]]])
Z([3,'请输入持票人姓名'])
Z([3,'color:#D1D1D1'])
Z([[7],[3,'registerName']])
Z(z[17])
Z(z[19])
Z(z[20])
Z(z[21])
Z(z[22])
Z([3,'证件类型'])
Z(z[25])
Z([3,'width:80%;'])
Z(z[2])
Z(z[24])
Z(z[24])
Z([3,'select-right-arrow data-v-bff0050c'])
Z([1,false])
Z([[4],[[5],[[5],[[4],[[5],[[5],[1,'^change']],[[4],[[5],[[4],[[5],[1,'change']]]]]]]],[[4],[[5],[[5],[1,'^input']],[[4],[[5],[[4],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'']],[1,'registerIdType']],[1,'$event']],[[4],[[5]]]]]]]]]]]]])
Z([[7],[3,'doucument']])
Z([[7],[3,'registerIdType']])
Z([3,'9020c9ec-2'])
Z(z[17])
Z(z[19])
Z(z[20])
Z(z[21])
Z(z[22])
Z([3,'证件号码'])
Z(z[24])
Z(z[25])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[1,'getInputValue']],[[4],[[5],[[5],[1,3]],[1,'$event']]]]]]]]]]])
Z([3,'18'])
Z([3,'请输入持票人证件号码'])
Z(z[28])
Z([[7],[3,'registerIdCard']])
Z(z[17])
Z(z[19])
Z(z[20])
Z(z[21])
Z(z[22])
Z([3,'手机号'])
Z(z[24])
Z(z[25])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[1,'getInputValue']],[[4],[[5],[[5],[1,1]],[1,'$event']]]]]]]]]]])
Z([1,true])
Z([3,'11'])
Z([3,'请输入手机号'])
Z(z[28])
Z([3,'number'])
Z([[7],[3,'registerPhone']])
Z(z[17])
Z([[7],[3,'activityCodeControl']])
Z(z[19])
Z(z[20])
Z(z[21])
Z(z[22])
Z([3,'激活码'])
Z(z[24])
Z(z[25])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[1,'getInputValue']],[[4],[[5],[[5],[1,4]],[1,'$event']]]]]]]]]]])
Z([3,'请输入邀请函上面的激活码'])
Z(z[28])
Z(z[73])
Z([[7],[3,'activityCode']])
Z(z[76])
Z(z[17])
Z(z[0])
Z([3,'display:flex;flex-direction:row;'])
Z(z[0])
Z([[6],[[7],[3,'$root']],[3,'m1']])
Z([3,'width:30rpx;height:30rpx;'])
Z([3,'yidu data-v-bff0050c'])
Z([3,'点击确定表示您已阅读并同意'])
Z(z[24])
Z([3,'realNameTips data-v-bff0050c'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'realNameTips']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'《实名须知》'])
Z(z[24])
Z([3,'save data-v-bff0050c'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'saveActivate']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'确定'])
Z([3,'bootom_icon data-v-bff0050c'])
Z([[6],[[7],[3,'$root']],[3,'m2']])
Z(z[2])
Z([3,'data-v-bff0050c vue-ref'])
Z([3,'popup'])
Z([3,'bottom'])
Z([3,'9020c9ec-3'])
Z([[4],[[5],[1,'default']]])
Z([3,'content-pop data-v-bff0050c'])
Z(z[2])
Z(z[24])
Z(z[0])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'closeRealNameExplain']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([[2,'+'],[[2,'+'],[1,'9020c9ec-4'],[1,',']],[1,'9020c9ec-3']])
Z(z[2])
Z(z[109])
Z([3,'confirm'])
Z([3,'9020c9ec-5'])
Z(z[2])
Z(z[109])
Z([3,'verifycode'])
Z([3,'9020c9ec-6'])
})(__WXML_GLOBAL__.ops_cached.$gwx4_XC_1_2);return __WXML_GLOBAL__.ops_cached.$gwx4_XC_1_2
}
__WXML_GLOBAL__.ops_set.$gwx4_XC_1=z;
__WXML_GLOBAL__.ops_init.$gwx4_XC_1=true;
var x=['./pages_wallet/components/realnameexplain/realnameexplain.wxml','./pages_wallet/invitation/activate.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx4_XC_1_1()
var cMD=_n('view')
_rz(z,cMD,'class',0,e,s,gg)
var oND=_mz(z,'view',['bindtap',1,'class',1,'data-event-opts',2],[],e,s,gg)
var lOD=_n('view')
_rz(z,lOD,'class',4,e,s,gg)
var aPD=_oz(z,5,e,s,gg)
_(lOD,aPD)
_(oND,lOD)
var tQD=_mz(z,'image',['class',6,'src',1],[],e,s,gg)
_(oND,tQD)
_(cMD,oND)
var eRD=_n('view')
_rz(z,eRD,'class',8,e,s,gg)
var bSD=_oz(z,9,e,s,gg)
_(eRD,bSD)
_(cMD,eRD)
var oTD=_n('view')
_rz(z,oTD,'class',10,e,s,gg)
var xUD=_mz(z,'view',['bindtap',11,'class',1,'data-event-opts',2],[],e,s,gg)
var oVD=_oz(z,14,e,s,gg)
_(xUD,oVD)
_(oTD,xUD)
_(cMD,oTD)
_(r,cMD)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
d_[x[1]]={}
var m1=function(e,s,r,gg){
var z=gz$gwx4_XC_1_2()
var cXD=_n('view')
_rz(z,cXD,'class',0,e,s,gg)
var hYD=_v()
_(cXD,hYD)
if(_oz(z,1,e,s,gg)){hYD.wxVkey=1
var oZD=_mz(z,'customtitlebar',['bind:__l',2,'class',1,'title',2,'vueId',3],[],e,s,gg)
_(hYD,oZD)
}
var c1D=_n('view')
_rz(z,c1D,'class',6,e,s,gg)
var o2D=_mz(z,'view',['class',7,'style',1],[],e,s,gg)
var t5D=_mz(z,'view',['class',9,'style',1],[],e,s,gg)
var e6D=_mz(z,'image',['class',11,'src',1],[],e,s,gg)
_(t5D,e6D)
var b7D=_n('view')
_rz(z,b7D,'class',13,e,s,gg)
var o8D=_oz(z,14,e,s,gg)
_(b7D,o8D)
_(t5D,b7D)
_(o2D,t5D)
var x9D=_n('view')
_rz(z,x9D,'class',15,e,s,gg)
var o0D=_oz(z,16,e,s,gg)
_(x9D,o0D)
_(o2D,x9D)
var fAE=_mz(z,'view',['class',17,'style',1],[],e,s,gg)
_(o2D,fAE)
var cBE=_n('view')
_rz(z,cBE,'class',19,e,s,gg)
var hCE=_n('view')
_rz(z,hCE,'class',20,e,s,gg)
var oDE=_oz(z,21,e,s,gg)
_(hCE,oDE)
_(cBE,hCE)
var cEE=_n('view')
_rz(z,cEE,'class',22,e,s,gg)
var oFE=_oz(z,23,e,s,gg)
_(cEE,oFE)
_(cBE,cEE)
var lGE=_mz(z,'input',['bindinput',24,'class',1,'data-event-opts',2,'placeholder',3,'placeholderStyle',4,'value',5],[],e,s,gg)
_(cBE,lGE)
_(o2D,cBE)
var aHE=_n('view')
_rz(z,aHE,'class',30,e,s,gg)
_(o2D,aHE)
var tIE=_n('view')
_rz(z,tIE,'class',31,e,s,gg)
var eJE=_n('view')
_rz(z,eJE,'class',32,e,s,gg)
var bKE=_oz(z,33,e,s,gg)
_(eJE,bKE)
_(tIE,eJE)
var oLE=_n('view')
_rz(z,oLE,'class',34,e,s,gg)
var xME=_oz(z,35,e,s,gg)
_(oLE,xME)
_(tIE,oLE)
var oNE=_mz(z,'view',['class',36,'style',1],[],e,s,gg)
var fOE=_mz(z,'uni-data-select',['bind:__l',38,'bind:change',1,'bind:input',2,'class',3,'clear',4,'data-event-opts',5,'localdata',6,'value',7,'vueId',8],[],e,s,gg)
_(oNE,fOE)
_(tIE,oNE)
_(o2D,tIE)
var cPE=_n('view')
_rz(z,cPE,'class',47,e,s,gg)
_(o2D,cPE)
var hQE=_n('view')
_rz(z,hQE,'class',48,e,s,gg)
var oRE=_n('view')
_rz(z,oRE,'class',49,e,s,gg)
var cSE=_oz(z,50,e,s,gg)
_(oRE,cSE)
_(hQE,oRE)
var oTE=_n('view')
_rz(z,oTE,'class',51,e,s,gg)
var lUE=_oz(z,52,e,s,gg)
_(oTE,lUE)
_(hQE,oTE)
var aVE=_mz(z,'input',['bindinput',53,'class',1,'data-event-opts',2,'maxlength',3,'placeholder',4,'placeholderStyle',5,'value',6],[],e,s,gg)
_(hQE,aVE)
_(o2D,hQE)
var tWE=_n('view')
_rz(z,tWE,'class',60,e,s,gg)
_(o2D,tWE)
var eXE=_n('view')
_rz(z,eXE,'class',61,e,s,gg)
var bYE=_n('view')
_rz(z,bYE,'class',62,e,s,gg)
var oZE=_oz(z,63,e,s,gg)
_(bYE,oZE)
_(eXE,bYE)
var x1E=_n('view')
_rz(z,x1E,'class',64,e,s,gg)
var o2E=_oz(z,65,e,s,gg)
_(x1E,o2E)
_(eXE,x1E)
var f3E=_mz(z,'input',['bindinput',66,'class',1,'data-event-opts',2,'disabled',3,'maxlength',4,'placeholder',5,'placeholderStyle',6,'type',7,'value',8],[],e,s,gg)
_(eXE,f3E)
_(o2D,eXE)
var c4E=_n('view')
_rz(z,c4E,'class',75,e,s,gg)
_(o2D,c4E)
var l3D=_v()
_(o2D,l3D)
if(_oz(z,76,e,s,gg)){l3D.wxVkey=1
var h5E=_n('view')
_rz(z,h5E,'class',77,e,s,gg)
var o6E=_n('view')
_rz(z,o6E,'class',78,e,s,gg)
var c7E=_oz(z,79,e,s,gg)
_(o6E,c7E)
_(h5E,o6E)
var o8E=_n('view')
_rz(z,o8E,'class',80,e,s,gg)
var l9E=_oz(z,81,e,s,gg)
_(o8E,l9E)
_(h5E,o8E)
var a0E=_mz(z,'input',['bindinput',82,'class',1,'data-event-opts',2,'placeholder',3,'placeholderStyle',4,'type',5,'value',6],[],e,s,gg)
_(h5E,a0E)
_(l3D,h5E)
}
var a4D=_v()
_(o2D,a4D)
if(_oz(z,89,e,s,gg)){a4D.wxVkey=1
var tAF=_n('view')
_rz(z,tAF,'class',90,e,s,gg)
_(a4D,tAF)
}
l3D.wxXCkey=1
a4D.wxXCkey=1
_(c1D,o2D)
var eBF=_mz(z,'view',['class',91,'style',1],[],e,s,gg)
var bCF=_mz(z,'image',['class',93,'src',1,'style',2],[],e,s,gg)
_(eBF,bCF)
var oDF=_n('view')
_rz(z,oDF,'class',96,e,s,gg)
var xEF=_oz(z,97,e,s,gg)
_(oDF,xEF)
_(eBF,oDF)
var oFF=_mz(z,'view',['bindtap',98,'class',1,'data-event-opts',2],[],e,s,gg)
var fGF=_oz(z,101,e,s,gg)
_(oFF,fGF)
_(eBF,oFF)
_(c1D,eBF)
var cHF=_mz(z,'view',['bindtap',102,'class',1,'data-event-opts',2],[],e,s,gg)
var hIF=_oz(z,105,e,s,gg)
_(cHF,hIF)
_(c1D,cHF)
var oJF=_mz(z,'image',['class',106,'src',1],[],e,s,gg)
_(c1D,oJF)
var cKF=_mz(z,'uni-popup',['bind:__l',108,'class',1,'data-ref',2,'type',3,'vueId',4,'vueSlots',5],[],e,s,gg)
var oLF=_n('view')
_rz(z,oLF,'class',114,e,s,gg)
var lMF=_mz(z,'realnameexplain',['bind:__l',115,'bindtap',1,'class',2,'data-event-opts',3,'vueId',4],[],e,s,gg)
_(oLF,lMF)
_(cKF,oLF)
_(c1D,cKF)
_(cXD,c1D)
var aNF=_mz(z,'pup-limit',['bind:__l',120,'class',1,'data-ref',2,'vueId',3],[],e,s,gg)
_(cXD,aNF)
var tOF=_mz(z,'verify-code-popup',['bind:__l',124,'class',1,'data-ref',2,'vueId',3],[],e,s,gg)
_(cXD,tOF)
hYD.wxXCkey=1
hYD.wxXCkey=3
_(r,cXD)
return r
}
e_[x[1]]={f:m1,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx4_XC_1";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx4_XC_1();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages_wallet/components/realnameexplain/realnameexplain.wxml'] = [$gwx4_XC_1, './pages_wallet/components/realnameexplain/realnameexplain.wxml'];else __wxAppCode__['pages_wallet/components/realnameexplain/realnameexplain.wxml'] = $gwx4_XC_1( './pages_wallet/components/realnameexplain/realnameexplain.wxml' );
		if (__vd_version_info__.delayedGwx) __wxAppCode__['pages_wallet/invitation/activate.wxml'] = [$gwx4_XC_1, './pages_wallet/invitation/activate.wxml'];else __wxAppCode__['pages_wallet/invitation/activate.wxml'] = $gwx4_XC_1( './pages_wallet/invitation/activate.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages_wallet/components/realnameexplain/realnameexplain.wxss'] = setCssToHead([".",[1],"eventdetail.",[1],"data-v-73bbb264{background-color:#fff;border-radius:",[0,30]," ",[0,30]," ",[0,0]," ",[0,0],";display:flex;flex-direction:column;height:",[0,900],";width:100%}\n.",[1],"eventdetail .",[1],"titlegroup.",[1],"data-v-73bbb264{display:flex;flex-direction:row;padding-top:",[0,50],";width:100%}\n.",[1],"eventdetail .",[1],"titlegroup .",[1],"title.",[1],"data-v-73bbb264{color:#000;font-size:",[0,34],";font-weight:700;padding-left:",[0,32],";width:100%}\n.",[1],"eventdetail .",[1],"titlegroup wx-image.",[1],"data-v-73bbb264{height:",[0,44],";margin-right:",[0,32],";width:",[0,50],"}\n.",[1],"eventdetail .",[1],"explain.",[1],"data-v-73bbb264{color:#999;font-size:",[0,28],";padding:",[0,20]," ",[0,32]," ",[0,0],"}\n.",[1],"eventdetail .",[1],"bottom.",[1],"data-v-73bbb264{align-items:center;bottom:",[0,0],";display:flex;flex-direction:row;height:",[0,150],";justify-content:space-around;position:fixed;width:100%}\n.",[1],"eventdetail .",[1],"bottom .",[1],"save.",[1],"data-v-73bbb264{background:linear-gradient(90deg,#000,rgba(0,0,0,.6));border-radius:",[0,50],";color:#fff;font-size:",[0,30],";height:",[0,88],";line-height:",[0,88],";text-align:center;width:90%}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages_wallet/components/realnameexplain/realnameexplain.wxss:1:396)",{path:"./pages_wallet/components/realnameexplain/realnameexplain.wxss"});__wxAppCode__['pages_wallet/invitation/activate.wxss'] = setCssToHead(["body{background:linear-gradient(180deg,#fff,#fcfcff 19%,#eaefff 68%)}\n.",[1],"content.",[1],"data-v-bff0050c{align-items:center;display:flex;flex-direction:column;overflow-x:hidden;width:100%}\n.",[1],"content .",[1],"bodyContent.",[1],"data-v-bff0050c{background-image:url(https://res.dasheng.top/app/icon/activate_bg.png);background-size:100% 100%;display:flex;flex-direction:column;margin-left:",[0,56],";margin-top:",[0,120],";padding-left:",[0,40],";width:",[0,670],"}\n.",[1],"content .",[1],"bodyContent .",[1],"img-tip.",[1],"data-v-bff0050c{height:",[0,48],";width:",[0,48],"}\n.",[1],"content .",[1],"bodyContent .",[1],"b-title.",[1],"data-v-bff0050c{color:#161616;font-size:",[0,40],";font-weight:700}\n.",[1],"content .",[1],"bodyContent .",[1],"s-title.",[1],"data-v-bff0050c{color:#999;font-size:",[0,28],";margin-left:",[0,100],";margin-top:",[0,24],"}\n.",[1],"content .",[1],"bodyContent .",[1],"line.",[1],"data-v-bff0050c{border:",[0,.5]," dashed #8d98a3;height:",[0,0],";opacity:.0991;width:",[0,560],"}\n.",[1],"content .",[1],"bodyContent .",[1],"itembg.",[1],"data-v-bff0050c{align-items:center;display:flex;flex-direction:row;height:",[0,120],";line-height:",[0,120],";width:",[0,560],"}\n.",[1],"content .",[1],"bodyContent .",[1],"xing.",[1],"data-v-bff0050c{color:#ea0000;font-size:",[0,30],"}\n.",[1],"content .",[1],"bodyContent .",[1],"lefttitle.",[1],"data-v-bff0050c{color:#333;font-size:",[0,30],";width:",[0,160],"}\n.",[1],"content .",[1],"bodyContent .",[1],"inputPhone.",[1],"data-v-bff0050c{color:#1a1a1a;font-size:",[0,30],";text-align:right;width:100%}\n.",[1],"content .",[1],"yidu.",[1],"data-v-bff0050c{color:#cbcaca;font-size:",[0,24],"}\n.",[1],"content .",[1],"realNameTips.",[1],"data-v-bff0050c{color:#1a1a1a;font-size:",[0,24],"}\n.",[1],"content .",[1],"save.",[1],"data-v-bff0050c{background:linear-gradient(90deg,#000,rgba(0,0,0,.6));border-radius:",[0,60],";color:#fff;font-size:",[0,34],";font-weight:700;height:",[0,88],";line-height:",[0,88],";margin:",[0,16]," ",[0,90]," ",[0,0],";text-align:center;width:",[0,570],";z-index:1}\n.",[1],"content .",[1],"bootom_icon.",[1],"data-v-bff0050c{bottom:",[0,0],";height:",[0,270],";position:fixed;width:100%}\n.",[1],"content .",[1],"select-right-arrow.",[1],"data-v-bff0050c .",[1],"uni-popper__arrow{left:86%}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages_wallet/invitation/activate.wxss:1:1)",{path:"./pages_wallet/invitation/activate.wxss"});
}