$gwx4_XC_7=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx4_XC_7 || [];
function gz$gwx4_XC_7_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx4_XC_7_1)return __WXML_GLOBAL__.ops_cached.$gwx4_XC_7_1
__WXML_GLOBAL__.ops_cached.$gwx4_XC_7_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'contentdetail data-v-97c74124'])
Z([[2,'!='],[[7],[3,'platform']],[1,'TT']])
Z([3,'transparent'])
Z([3,'__l'])
Z([3,'__e'])
Z([1,false])
Z([3,'data-v-97c74124'])
Z([3,'#ffffff'])
Z([[4],[[5],[[4],[[5],[[5],[1,'^clickLeft']],[[4],[[5],[[4],[[5],[1,'back']]]]]]]]])
Z([1,true])
Z([[2,'?:'],[[2,'!='],[[7],[3,'platform']],[1,'ALI']],[1,'left'],[1,'']])
Z(z[9])
Z([3,'票详情'])
Z([3,'52f7e95e-1'])
Z([3,'mainBg data-v-97c74124'])
Z([3,'topBlurImage data-v-97c74124'])
Z([[2,'+'],[[2,'+'],[1,'--bgurl:'],[[2,'+'],[[2,'+'],[1,'url('],[[7],[3,'pageImgBg']]],[1,')']]],[1,';']])
Z([3,'topBlurBlack data-v-97c74124'])
Z([3,'topBlackForeground data-v-97c74124'])
Z([[6],[[7],[3,'$root']],[3,'m0']])
Z([3,'mainContent data-v-97c74124'])
Z(z[4])
Z([3,'topLocation data-v-97c74124'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[1,'toMap']]]]]]]]])
Z(z[6])
Z([3,'display:flex;justify-content:space-between;align-items:center;height:80rpx;'])
Z([3,'locationName data-v-97c74124'])
Z([a,[[6],[[7],[3,'itemdata']],[3,'venueName']]])
Z(z[6])
Z([[6],[[7],[3,'$root']],[3,'m1']])
Z([3,'ticketContent data-v-97c74124'])
Z([3,'ticketTop data-v-97c74124'])
Z(z[6])
Z([3,'height:20rpx;width:1px;'])
Z([3,'ticketTopContent data-v-97c74124'])
Z([3,'ticketDetail data-v-97c74124'])
Z([3,'tName data-v-97c74124'])
Z([a,[[6],[[7],[3,'itemdata']],[3,'performanceName']]])
Z([3,'tTime data-v-97c74124'])
Z([3,'margin-top:20rpx;'])
Z([a,[[6],[[7],[3,'itemdata']],[3,'timeIntervalText']]])
Z(z[38])
Z([3,'margin-top:8rpx;'])
Z([a,z[27][1]])
Z([3,'ticketImg data-v-97c74124'])
Z([[7],[3,'pageImgBg']])
Z(z[6])
Z([3,'scaleToFill'])
Z([[6],[[7],[3,'$root']],[3,'m2']])
Z([3,'width:100%;height:80rpx;'])
Z([3,'ticketMiddle data-v-97c74124'])
Z([3,'ticketIndex data-v-97c74124'])
Z([a,[[2,'+'],[[2,'+'],[[2,'+'],[[7],[3,'eleTicketIndex']],[1,1]],[1,'/']],[[6],[[7],[3,'$root']],[3,'g0']]]])
Z([3,'ticketMiddleContent data-v-97c74124'])
Z([3,'sessionsName data-v-97c74124'])
Z([a,[[6],[[7],[3,'itemdata']],[3,'showName']]])
Z([3,'sessionsTime data-v-97c74124'])
Z([a,[[6],[[7],[3,'$root']],[3,'f0']]])
Z([3,'qrCodeContent data-v-97c74124'])
Z(z[4])
Z([3,'preCode data-v-97c74124'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'arrowLeft']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([[6],[[7],[3,'$root']],[3,'m3']])
Z([3,'qrCodeBorder data-v-97c74124'])
Z([[7],[3,'isIdcardticket']])
Z([3,'idcard data-v-97c74124'])
Z([[4],[[5],[[5],[1,'data-v-97c74124']],[[7],[3,'idcardImageClass']]]])
Z([[7],[3,'previewImageUrl']])
Z([[4],[[5],[[5],[[5],[1,'data-v-97c74124']],[1,'qrcodegroup']],[[4],[[5],[[2,'?:'],[[7],[3,'isQrCodeGrouped']],[1,'qrcodegrouped'],[1,'']]]]]])
Z([[7],[3,'qrCode']])
Z([[7],[3,'currentStatusImage']])
Z([3,'warnImage data-v-97c74124'])
Z([[6],[[7],[3,'$root']],[3,'m4']])
Z(z[4])
Z([3,'nextCode data-v-97c74124'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'arrowRight']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([[6],[[7],[3,'$root']],[3,'m5']])
Z([[6],[[7],[3,'orderData']],[3,'registerName']])
Z([3,'holderName data-v-97c74124'])
Z([a,[[6],[[7],[3,'orderData']],[3,'registerName']]])
Z([[7],[3,'buyerName']])
Z(z[78])
Z([a,[[7],[3,'buyerName']]])
Z([3,'seatAndPrice data-v-97c74124'])
Z([a,[[2,'+'],[[2,'+'],[[2,'+'],[[2,'+'],[[2,'+'],[1,''],[[7],[3,'seatAndPriceStr']]],[[2,'+'],[[7],[3,'eleTicketIndex']],[1,1]]],[1,'/']],[[6],[[7],[3,'$root']],[3,'g1']]],[1,'张']]])
Z([3,'seatNo data-v-97c74124'])
Z([3,'nbsp'])
Z([a,[[2,'+'],[1,'T.N:  '],[[6],[[7],[3,'orderData']],[3,'documentCode']]]])
Z([[2,'&&'],[[2,'&&'],[[2,'&&'],[[2,'&&'],[[2,'&&'],[[2,'&&'],[[7],[3,'openToGift']],[[7],[3,'isRangeTime']]],[[2,'=='],[[7],[3,'navIndex']],[1,1]]],[[7],[3,'isIdcardticket']]],[[2,'!='],[[7],[3,'drawOutType']],[1,'8']]],[[2,'=='],[[7],[3,'status']],[1,0]]],[[2,'<'],[[6],[[7],[3,'orderData']],[3,'translateTimes']],[1,1]]])
Z(z[4])
Z([3,'transfer data-v-97c74124'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'goTransfer']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'转赠'])
Z(z[6])
Z(z[47])
Z([[6],[[7],[3,'$root']],[3,'m6']])
Z(z[49])
Z([3,'ticketBottom data-v-97c74124'])
Z([[2,'&&'],[[2,'&&'],[[2,'=='],[[6],[[7],[3,'orderData']],[3,'invitationActivateStatus']],[1,0]],[[2,'!='],[[7],[3,'navIndex']],[1,0]]],[[7],[3,'displayDetailButton']]])
Z(z[4])
Z([3,'toOrderDetail data-v-97c74124'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'jumpOrderDetail']],[[4],[[5],[1,'$0']]]],[[4],[[5],[[2,'+'],[[2,'+'],[1,'ticketIds.'],[[7],[3,'eleTicketIndex']]],[1,'.orderId']]]]]]]]]]]])
Z([3,'orderDetailTitle data-v-97c74124'])
Z([3,'订单详情'])
Z(z[6])
Z([3,'display:flex;align-items:center;'])
Z(z[6])
Z([3,'font-size:24rpx;line-height:36rpx;color:#666666;'])
Z([3,'查看'])
Z(z[6])
Z([[6],[[7],[3,'$root']],[3,'m7']])
Z([3,'width:24rpx;height:24rpx;'])
Z([[2,'&&'],[[2,'=='],[[6],[[7],[3,'orderData']],[3,'invitationActivateStatus']],[1,0]],[[2,'!='],[[7],[3,'navIndex']],[1,0]]])
Z([3,'soildLine data-v-97c74124'])
Z([[7],[3,'electTicketTipsTitle']])
Z([3,'wxts data-v-97c74124'])
Z(z[6])
Z([[6],[[7],[3,'$root']],[3,'m8']])
Z([3,'width:32rpx;height:32rpx;'])
Z([3,'wxts-title data-v-97c74124'])
Z([a,[[7],[3,'electTicketTipsTitle']]])
Z([[7],[3,'electTicketTips']])
Z([3,'bottomTip data-v-97c74124'])
Z([a,[[7],[3,'electTicketTips']]])
Z(z[6])
Z([[6],[[7],[3,'$root']],[3,'m9']])
Z(z[49])
Z(z[3])
Z([3,'data-v-97c74124 vue-ref'])
Z([3,'popupqpaddress'])
Z([3,'bottom'])
Z([3,'52f7e95e-2'])
Z([[4],[[5],[1,'default']]])
Z([3,'content-pop data-v-97c74124'])
Z([[7],[3,'addressAar']])
Z(z[3])
Z(z[4])
Z(z[6])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'closeQPAddress']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([[2,'+'],[[2,'+'],[1,'52f7e95e-3'],[1,',']],[1,'52f7e95e-2']])
Z(z[3])
Z(z[128])
Z([3,'confirm'])
Z([3,'52f7e95e-4'])
Z(z[3])
Z(z[128])
Z([3,'verifycode'])
Z([3,'52f7e95e-5'])
})(__WXML_GLOBAL__.ops_cached.$gwx4_XC_7_1);return __WXML_GLOBAL__.ops_cached.$gwx4_XC_7_1
}
__WXML_GLOBAL__.ops_set.$gwx4_XC_7=z;
__WXML_GLOBAL__.ops_init.$gwx4_XC_7=true;
var x=['./pages_wallet/wallet/ticketEvent.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx4_XC_7_1()
var o0O=_n('view')
_rz(z,o0O,'class',0,e,s,gg)
var cAP=_v()
_(o0O,cAP)
if(_oz(z,1,e,s,gg)){cAP.wxVkey=1
var oBP=_mz(z,'uni-nav-bar',['backgroundColor',2,'bind:__l',1,'bind:clickLeft',2,'border',3,'class',4,'color',5,'data-event-opts',6,'fixed',7,'leftIcon',8,'statusBar',9,'title',10,'vueId',11],[],e,s,gg)
_(cAP,oBP)
}
var lCP=_n('view')
_rz(z,lCP,'class',14,e,s,gg)
var aDP=_mz(z,'image',['class',15,'style',1],[],e,s,gg)
_(lCP,aDP)
var tEP=_n('view')
_rz(z,tEP,'class',17,e,s,gg)
_(lCP,tEP)
var eFP=_mz(z,'image',['class',18,'src',1],[],e,s,gg)
_(lCP,eFP)
_(o0O,lCP)
var bGP=_n('view')
_rz(z,bGP,'class',20,e,s,gg)
var oHP=_mz(z,'view',['bindtap',21,'class',1,'data-event-opts',2],[],e,s,gg)
var xIP=_mz(z,'view',['class',24,'style',1],[],e,s,gg)
var oJP=_n('text')
_rz(z,oJP,'class',26,e,s,gg)
var fKP=_oz(z,27,e,s,gg)
_(oJP,fKP)
_(xIP,oJP)
var cLP=_mz(z,'image',['class',28,'src',1],[],e,s,gg)
_(xIP,cLP)
_(oHP,xIP)
_(bGP,oHP)
var hMP=_n('view')
_rz(z,hMP,'class',30,e,s,gg)
var oNP=_n('view')
_rz(z,oNP,'class',31,e,s,gg)
var cOP=_mz(z,'view',['class',32,'style',1],[],e,s,gg)
_(oNP,cOP)
var oPP=_n('view')
_rz(z,oPP,'class',34,e,s,gg)
var lQP=_n('view')
_rz(z,lQP,'class',35,e,s,gg)
var aRP=_n('text')
_rz(z,aRP,'class',36,e,s,gg)
var tSP=_oz(z,37,e,s,gg)
_(aRP,tSP)
_(lQP,aRP)
var eTP=_mz(z,'text',['class',38,'style',1],[],e,s,gg)
var bUP=_oz(z,40,e,s,gg)
_(eTP,bUP)
_(lQP,eTP)
var oVP=_mz(z,'text',['class',41,'style',1],[],e,s,gg)
var xWP=_oz(z,43,e,s,gg)
_(oVP,xWP)
_(lQP,oVP)
_(oPP,lQP)
var oXP=_mz(z,'image',['class',44,'src',1],[],e,s,gg)
_(oPP,oXP)
_(oNP,oPP)
_(hMP,oNP)
var fYP=_mz(z,'image',['class',46,'mode',1,'src',2,'style',3],[],e,s,gg)
_(hMP,fYP)
var cZP=_n('view')
_rz(z,cZP,'class',50,e,s,gg)
var h1P=_n('text')
_rz(z,h1P,'class',51,e,s,gg)
var o2P=_oz(z,52,e,s,gg)
_(h1P,o2P)
_(cZP,h1P)
var c3P=_n('view')
_rz(z,c3P,'class',53,e,s,gg)
var a6P=_n('text')
_rz(z,a6P,'class',54,e,s,gg)
var t7P=_oz(z,55,e,s,gg)
_(a6P,t7P)
_(c3P,a6P)
var e8P=_n('text')
_rz(z,e8P,'class',56,e,s,gg)
var b9P=_oz(z,57,e,s,gg)
_(e8P,b9P)
_(c3P,e8P)
var o0P=_n('view')
_rz(z,o0P,'class',58,e,s,gg)
var xAQ=_mz(z,'image',['bindtap',59,'class',1,'data-event-opts',2,'src',3],[],e,s,gg)
_(o0P,xAQ)
var oBQ=_n('view')
_rz(z,oBQ,'class',63,e,s,gg)
var fCQ=_v()
_(oBQ,fCQ)
if(_oz(z,64,e,s,gg)){fCQ.wxVkey=1
var hEQ=_n('view')
_rz(z,hEQ,'class',65,e,s,gg)
var oFQ=_mz(z,'image',['class',66,'src',1],[],e,s,gg)
_(hEQ,oFQ)
_(fCQ,hEQ)
}
else{fCQ.wxVkey=2
var cGQ=_mz(z,'image',['class',68,'src',1],[],e,s,gg)
_(fCQ,cGQ)
}
var cDQ=_v()
_(oBQ,cDQ)
if(_oz(z,70,e,s,gg)){cDQ.wxVkey=1
var oHQ=_mz(z,'image',['class',71,'src',1],[],e,s,gg)
_(cDQ,oHQ)
}
fCQ.wxXCkey=1
cDQ.wxXCkey=1
_(o0P,oBQ)
var lIQ=_mz(z,'image',['bindtap',73,'class',1,'data-event-opts',2,'src',3],[],e,s,gg)
_(o0P,lIQ)
_(c3P,o0P)
var o4P=_v()
_(c3P,o4P)
if(_oz(z,77,e,s,gg)){o4P.wxVkey=1
var aJQ=_n('text')
_rz(z,aJQ,'class',78,e,s,gg)
var tKQ=_oz(z,79,e,s,gg)
_(aJQ,tKQ)
_(o4P,aJQ)
}
else{o4P.wxVkey=2
var eLQ=_v()
_(o4P,eLQ)
if(_oz(z,80,e,s,gg)){eLQ.wxVkey=1
var bMQ=_n('text')
_rz(z,bMQ,'class',81,e,s,gg)
var oNQ=_oz(z,82,e,s,gg)
_(bMQ,oNQ)
_(eLQ,bMQ)
}
eLQ.wxXCkey=1
}
var xOQ=_n('view')
_rz(z,xOQ,'class',83,e,s,gg)
var oPQ=_oz(z,84,e,s,gg)
_(xOQ,oPQ)
_(c3P,xOQ)
var fQQ=_mz(z,'text',['class',85,'space',1],[],e,s,gg)
var cRQ=_oz(z,87,e,s,gg)
_(fQQ,cRQ)
_(c3P,fQQ)
var l5P=_v()
_(c3P,l5P)
if(_oz(z,88,e,s,gg)){l5P.wxVkey=1
var hSQ=_mz(z,'view',['bindtap',89,'class',1,'data-event-opts',2],[],e,s,gg)
var oTQ=_oz(z,92,e,s,gg)
_(hSQ,oTQ)
_(l5P,hSQ)
}
o4P.wxXCkey=1
l5P.wxXCkey=1
_(cZP,c3P)
_(hMP,cZP)
var cUQ=_mz(z,'image',['class',93,'mode',1,'src',2,'style',3],[],e,s,gg)
_(hMP,cUQ)
var oVQ=_n('view')
_rz(z,oVQ,'class',97,e,s,gg)
var lWQ=_v()
_(oVQ,lWQ)
if(_oz(z,98,e,s,gg)){lWQ.wxVkey=1
var b1Q=_mz(z,'view',['bindtap',99,'class',1,'data-event-opts',2],[],e,s,gg)
var o2Q=_n('text')
_rz(z,o2Q,'class',102,e,s,gg)
var x3Q=_oz(z,103,e,s,gg)
_(o2Q,x3Q)
_(b1Q,o2Q)
var o4Q=_mz(z,'view',['class',104,'style',1],[],e,s,gg)
var f5Q=_mz(z,'text',['class',106,'style',1],[],e,s,gg)
var c6Q=_oz(z,108,e,s,gg)
_(f5Q,c6Q)
_(o4Q,f5Q)
var h7Q=_mz(z,'image',['class',109,'src',1,'style',2],[],e,s,gg)
_(o4Q,h7Q)
_(b1Q,o4Q)
_(lWQ,b1Q)
}
var aXQ=_v()
_(oVQ,aXQ)
if(_oz(z,112,e,s,gg)){aXQ.wxVkey=1
var o8Q=_n('view')
_rz(z,o8Q,'class',113,e,s,gg)
_(aXQ,o8Q)
}
var tYQ=_v()
_(oVQ,tYQ)
if(_oz(z,114,e,s,gg)){tYQ.wxVkey=1
var c9Q=_n('view')
_rz(z,c9Q,'class',115,e,s,gg)
var o0Q=_mz(z,'image',['class',116,'src',1,'style',2],[],e,s,gg)
_(c9Q,o0Q)
var lAR=_n('text')
_rz(z,lAR,'class',119,e,s,gg)
var aBR=_oz(z,120,e,s,gg)
_(lAR,aBR)
_(c9Q,lAR)
_(tYQ,c9Q)
}
var eZQ=_v()
_(oVQ,eZQ)
if(_oz(z,121,e,s,gg)){eZQ.wxVkey=1
var tCR=_n('text')
_rz(z,tCR,'class',122,e,s,gg)
var eDR=_oz(z,123,e,s,gg)
_(tCR,eDR)
_(eZQ,tCR)
}
lWQ.wxXCkey=1
aXQ.wxXCkey=1
tYQ.wxXCkey=1
eZQ.wxXCkey=1
_(hMP,oVQ)
var bER=_mz(z,'image',['class',124,'src',1,'style',2],[],e,s,gg)
_(hMP,bER)
_(bGP,hMP)
_(o0O,bGP)
var oFR=_mz(z,'uni-popup',['bind:__l',127,'class',1,'data-ref',2,'type',3,'vueId',4,'vueSlots',5],[],e,s,gg)
var xGR=_n('view')
_rz(z,xGR,'class',133,e,s,gg)
var oHR=_mz(z,'ticketaddress',['addressAar',134,'bind:__l',1,'bindtap',2,'class',3,'data-event-opts',4,'vueId',5],[],e,s,gg)
_(xGR,oHR)
_(oFR,xGR)
_(o0O,oFR)
var fIR=_mz(z,'pup-limit',['bind:__l',140,'class',1,'data-ref',2,'vueId',3],[],e,s,gg)
_(o0O,fIR)
var cJR=_mz(z,'verify-code-popup',['bind:__l',144,'class',1,'data-ref',2,'vueId',3],[],e,s,gg)
_(o0O,cJR)
cAP.wxXCkey=1
cAP.wxXCkey=3
_(r,o0O)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx4_XC_7";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx4_XC_7();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages_wallet/wallet/ticketEvent.wxml'] = [$gwx4_XC_7, './pages_wallet/wallet/ticketEvent.wxml'];else __wxAppCode__['pages_wallet/wallet/ticketEvent.wxml'] = $gwx4_XC_7( './pages_wallet/wallet/ticketEvent.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages_wallet/wallet/ticketEvent.wxss'] = setCssToHead([".",[1],"contentdetail.",[1],"data-v-97c74124{display:flex;flex-direction:column;height:100vh;justify-content:center}\n.",[1],"contentdetail .",[1],"mainBg.",[1],"data-v-97c74124{height:100vh;left:0;overflow:hidden;position:fixed;top:0;width:100%;z-index:-1}\n.",[1],"contentdetail .",[1],"mainBg .",[1],"topBlurImage.",[1],"data-v-97c74124{background:var(--bgurl);background-size:100% 100%;-webkit-filter:blur(50px) brightness(1.2);filter:blur(50px) brightness(1.2);height:120%;margin:-10%;position:absolute;width:120%}\n.",[1],"contentdetail .",[1],"mainBg .",[1],"topBlurBlack.",[1],"data-v-97c74124{background-color:#000;background-size:100% 100%;height:100%;opacity:.7;position:absolute;width:100%}\n.",[1],"contentdetail .",[1],"mainBg .",[1],"topBlackForeground.",[1],"data-v-97c74124{height:100%;position:absolute;width:100%}\n.",[1],"contentdetail .",[1],"mainContent.",[1],"data-v-97c74124{flex:1;margin-top:",[0,30],";overflow-y:auto;padding-left:",[0,40],";padding-right:",[0,40],";z-index:2}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"topLocation.",[1],"data-v-97c74124{background-image:url(https://res.dasheng.top/app/icon/wallet_detail_locatoin_bg.png);background-repeat:no-repeat;background-size:100% 100%;height:",[0,112],";width:100%}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"topLocation .",[1],"locationName.",[1],"data-v-97c74124{-webkit-line-clamp:1;-webkit-box-orient:vertical;color:#1a1a1a;display:-webkit-box;flex:1;font-size:",[0,28],";line-height:",[0,36],";margin-left:",[0,36],";margin-right:",[0,10],";overflow:hidden;text-overflow:ellipsis}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"topLocation wx-image.",[1],"data-v-97c74124{height:",[0,40],";margin-right:",[0,64],";width:",[0,40],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent.",[1],"data-v-97c74124{background-repeat:no-repeat;display:flex;flex-direction:column;margin-top:",[0,-32],";width:100%}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketTop.",[1],"data-v-97c74124{background-color:#fff;border-top-left-radius:",[0,24],";border-top-right-radius:",[0,24],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketTop .",[1],"ticketTopContent.",[1],"data-v-97c74124{display:flex;height:",[0,162],";width:100%}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketTop .",[1],"ticketTopContent .",[1],"ticketDetail.",[1],"data-v-97c74124{display:flex;flex:1;flex-direction:column;height:",[0,162],";margin-left:",[0,32],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketTop .",[1],"ticketTopContent .",[1],"ticketDetail .",[1],"tName.",[1],"data-v-97c74124{-webkit-line-clamp:2;-webkit-box-orient:vertical;color:#1a1a1a;display:-webkit-box;font-size:",[0,28],";font-weight:700;height:",[0,80],";line-height:",[0,40],";overflow:hidden;text-overflow:ellipsis}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketTop .",[1],"ticketTopContent .",[1],"ticketDetail .",[1],"tTime.",[1],"data-v-97c74124{-webkit-line-clamp:1;-webkit-box-orient:vertical;color:#999;display:-webkit-box;font-size:",[0,24],";line-height:",[0,32],";overflow:hidden;text-overflow:ellipsis}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketTop .",[1],"ticketTopContent .",[1],"ticketImg.",[1],"data-v-97c74124{border-radius:",[0,8],";height:",[0,148],";margin-left:",[0,32],";margin-right:",[0,32],";width:",[0,112],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle.",[1],"data-v-97c74124{background-color:#fff;padding-left:",[0,32],";padding-right:",[0,32],";position:relative}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketIndex.",[1],"data-v-97c74124{color:#1a1a1a;font-size:",[0,28],";left:",[0,36],";line-height:",[0,40],";position:absolute;top:",[0,0],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent.",[1],"data-v-97c74124{align-items:center;display:flex;flex-direction:column}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"sessionsName.",[1],"data-v-97c74124{color:#1a1a1a;font-size:",[0,28],";font-weight:700;line-height:",[0,40],";margin:",[0,8]," ",[0,70]," ",[0,0],";text-align:center}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"sessionsTime.",[1],"data-v-97c74124{color:#999;font-size:",[0,24],";line-height:",[0,32],";margin-top:",[0,8],";text-align:center}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent.",[1],"data-v-97c74124{align-items:center;display:flex;justify-content:space-between;margin-top:",[0,24],";width:100%}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"preCode.",[1],"data-v-97c74124{height:",[0,64],";margin-left:",[0,36],";width:",[0,64],"}\n@-webkit-keyframes rotate-data-v-97c74124{100%{-webkit-transform:rotate(1turn);transform:rotate(1turn)}\n}@keyframes rotate-data-v-97c74124{100%{-webkit-transform:rotate(1turn);transform:rotate(1turn)}\n}.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder.",[1],"data-v-97c74124{align-items:center;background:#fff;border:",[0,2]," solid #eee;border-radius:",[0,16],";box-sizing:border-box;display:flex;height:",[0,336],";justify-content:center;margin:0 auto;overflow:hidden;padding:",[0,5],";position:relative;width:",[0,342],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder.",[1],"data-v-97c74124::after{-webkit-animation:rotate-data-v-97c74124 4s linear infinite;animation:rotate-data-v-97c74124 4s linear infinite;background-image:conic-gradient(hsla(0,0%,100%,0) 1%,rgba(250,100,250,.2) 10%,#8bf1f9 15%,#6ff7b5 15%,hsla(0,0%,100%,0) 1%);border-radius:",[0,10],";content:\x22\x22;height:300%;left:-100%;overflow:hidden;position:absolute;top:-100%;width:300%;z-index:1}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder.",[1],"data-v-97c74124::before{background:#fff;border-radius:",[0,10],";content:\x22\x22;height:calc(100% - ",[0,12],");position:absolute;width:calc(100% - ",[0,12],");z-index:2}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder .",[1],"idcard.",[1],"data-v-97c74124{align-items:center;display:flex;flex-direction:column;z-index:5}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder .",[1],"idcardPlaceHolder.",[1],"data-v-97c74124{height:",[0,196],";width:",[0,302],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder .",[1],"idcardPlaceHolder-v.",[1],"data-v-97c74124{height:",[0,238],";width:",[0,190],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder .",[1],"forgetCard.",[1],"data-v-97c74124{align-items:center;border:1px solid rgba(96,172,255,.2);border-radius:",[0,20],";box-sizing:border-box;color:#60acff;font-size:",[0,20],";line-height:",[0,32],";margin-top:",[0,20],";padding:",[0,4]," ",[0,20],";text-align:center}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder .",[1],"warnImage.",[1],"data-v-97c74124{height:",[0,168],";left:0;margin:",[0,82]," ",[0,85],";position:absolute;top:0;width:",[0,168],";z-index:5}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"nextCode.",[1],"data-v-97c74124{height:",[0,64],";margin-right:",[0,36],";width:",[0,64],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"checknum.",[1],"data-v-97c74124{align-items:center;background-size:100% 100%;color:#fff;display:flex;font-size:",[0,24],";font-weight:700;height:",[0,60],";justify-content:center;margin-top:",[0,-30],";padding-top:",[0,6],";text-align:center;width:",[0,378],";z-index:99}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"holderName.",[1],"data-v-97c74124{color:#1a1a1a;font-size:",[0,28],";font-weight:700;line-height:",[0,40],";margin-top:",[0,20],";text-align:center}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"seatAndPrice.",[1],"data-v-97c74124{color:#666;font-size:",[0,24],";line-height:",[0,40],";margin-left:",[0,30],";margin-right:",[0,30],";margin-top:",[0,16],";text-align:center;white-space:pre-wrap}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"seatNo.",[1],"data-v-97c74124{border:1px solid #d8d8d8;border-radius:",[0,42],";color:#666;font-size:",[0,20],";height:",[0,42],";line-height:",[0,42],";margin-top:",[0,16],";padding:",[0,4]," ",[0,20],";text-align:center}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"transfer.",[1],"data-v-97c74124{background:#b2d7ff;border-radius:",[0,40],";color:#1a1a1a;font-size:",[0,24],";font-weight:500;height:",[0,52],";line-height:",[0,52],";margin-top:",[0,36],";text-align:center;width:",[0,112],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketBottom.",[1],"data-v-97c74124{background-color:#fff;margin-top:",[0,-1],";padding:",[0,0]," ",[0,32],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketBottom .",[1],"toOrderDetail.",[1],"data-v-97c74124{align-items:center;display:flex;justify-content:space-between}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketBottom .",[1],"toOrderDetail .",[1],"orderDetailTitle.",[1],"data-v-97c74124{color:#1a1a1a;font-size:",[0,28],";font-weight:700;line-height:",[0,40],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketBottom .",[1],"bottomTip.",[1],"data-v-97c74124{color:#666;font-size:",[0,24],";line-height:",[0,40],";margin-top:",[0,8],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"soildLine.",[1],"data-v-97c74124{background-color:#eee;height:",[0,1],";margin-top:",[0,28],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"wxts.",[1],"data-v-97c74124{align-items:center;display:flex;margin-top:",[0,20],";width:100%}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"wxts .",[1],"wxts-title.",[1],"data-v-97c74124{color:#1a1a1a;flex:1;font-size:",[0,28],";font-weight:700;line-height:",[0,40],";margin-left:",[0,8],"}\n.",[1],"contentdetail .",[1],"qrcodegroup.",[1],"data-v-97c74124{height:95%;width:95%;z-index:5}\n.",[1],"contentdetail .",[1],"qrcodegrouped.",[1],"data-v-97c74124{-webkit-filter:blur(3px);filter:blur(3px);opacity:.5}\n.",[1],"contentdetail .",[1],"content-pop.",[1],"data-v-97c74124{background-color:#fff;border-radius:",[0,25]," ",[0,25]," 0 0;height:70vh;width:100vw}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages_wallet/wallet/ticketEvent.wxss:1:1372)",{path:"./pages_wallet/wallet/ticketEvent.wxss"});
}