$gwx4_XC_6=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx4_XC_6 || [];
function gz$gwx4_XC_6_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx4_XC_6_1)return __WXML_GLOBAL__.ops_cached.$gwx4_XC_6_1
__WXML_GLOBAL__.ops_cached.$gwx4_XC_6_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'contentdetail data-v-cf130fde'])
Z([[2,'!='],[[7],[3,'platform']],[1,'TT']])
Z([3,'transparent'])
Z([3,'__l'])
Z([3,'__e'])
Z([1,false])
Z([3,'data-v-cf130fde'])
Z([3,'#ffffff'])
Z([[4],[[5],[[4],[[5],[[5],[1,'^clickLeft']],[[4],[[5],[[4],[[5],[1,'back']]]]]]]]])
Z([1,true])
Z([[2,'?:'],[[2,'!='],[[7],[3,'platform']],[1,'ALI']],[1,'left'],[1,'']])
Z(z[9])
Z([3,'票详情'])
Z([3,'eac12ac4-1'])
Z([3,'mainBg data-v-cf130fde'])
Z([3,'topBlurImage data-v-cf130fde'])
Z([[2,'+'],[[2,'+'],[1,'--bgurl:'],[[2,'+'],[[2,'+'],[1,'url('],[[7],[3,'pageImgBg']]],[1,')']]],[1,';']])
Z([3,'topBlurBlack data-v-cf130fde'])
Z([3,'topBlackForeground data-v-cf130fde'])
Z([[6],[[7],[3,'$root']],[3,'m0']])
Z([3,'mainContent data-v-cf130fde'])
Z(z[4])
Z([3,'topLocation data-v-cf130fde'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[1,'toMap']]]]]]]]])
Z(z[6])
Z([3,'display:flex;justify-content:space-between;align-items:center;height:80rpx;'])
Z([3,'locationName data-v-cf130fde'])
Z([a,[[6],[[7],[3,'itemdata']],[3,'venueName']]])
Z(z[6])
Z([[6],[[7],[3,'$root']],[3,'m1']])
Z([3,'ticketContent data-v-cf130fde'])
Z([3,'ticketTop data-v-cf130fde'])
Z(z[6])
Z([3,'height:20rpx;width:1px;'])
Z([3,'ticketTopContent data-v-cf130fde'])
Z([3,'ticketDetail data-v-cf130fde'])
Z([3,'tName data-v-cf130fde'])
Z([a,[[6],[[7],[3,'itemdata']],[3,'name']]])
Z([3,'tTime data-v-cf130fde'])
Z([3,'margin-top:20rpx;'])
Z([a,[[6],[[7],[3,'itemdata']],[3,'timeIntervalText']]])
Z(z[38])
Z([3,'margin-top:8rpx;'])
Z([a,z[27][1]])
Z([3,'ticketImg data-v-cf130fde'])
Z([[7],[3,'pageImgBg']])
Z(z[6])
Z([3,'scaleToFill'])
Z([[6],[[7],[3,'$root']],[3,'m2']])
Z([3,'width:100%;height:80rpx;'])
Z([3,'ticketMiddle data-v-cf130fde'])
Z([3,'ticketIndex data-v-cf130fde'])
Z([a,[[2,'+'],[[2,'+'],[[2,'+'],[[7],[3,'eleTicketIndex']],[1,1]],[1,'/']],[[6],[[7],[3,'$root']],[3,'g0']]]])
Z([3,'ticketMiddleContent data-v-cf130fde'])
Z([3,'sessionsName data-v-cf130fde'])
Z([a,[[6],[[7],[3,'itemdata']],[3,'showName']]])
Z([3,'sessionsTime data-v-cf130fde'])
Z([a,[[6],[[7],[3,'$root']],[3,'f0']]])
Z([3,'qrCodeContent data-v-cf130fde'])
Z(z[4])
Z([3,'preCode data-v-cf130fde'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'arrowLeft']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([[6],[[7],[3,'$root']],[3,'m3']])
Z([3,'qrCodeBorder data-v-cf130fde'])
Z([3,'ticketCode data-v-cf130fde'])
Z([a,[[2,'+'],[[2,'+'],[1,'取票码：'],[[7],[3,'ticketCode']]],[1,'']]])
Z([[4],[[5],[[5],[1,'data-v-cf130fde']],[[2,'?:'],[[2,'>='],[[7],[3,'status']],[1,1]],[1,'classgrouped'],[1,'']]]])
Z([[7],[3,'qrCode']])
Z([3,'width:278rpx;height:280rpx;z-index:5;margin-top:16rpx;'])
Z([[2,'>'],[[7],[3,'status']],[1,0]])
Z(z[6])
Z([[2,'=='],[[7],[3,'status']],[1,1]])
Z([3,'warnImage data-v-cf130fde'])
Z([[6],[[7],[3,'$root']],[3,'m4']])
Z([[2,'=='],[[7],[3,'status']],[1,2]])
Z(z[72])
Z([[6],[[7],[3,'$root']],[3,'m5']])
Z([[2,'=='],[[7],[3,'status']],[1,3]])
Z(z[72])
Z([[6],[[7],[3,'$root']],[3,'m6']])
Z(z[4])
Z([3,'nextCode data-v-cf130fde'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'arrowRight']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([[6],[[7],[3,'$root']],[3,'m7']])
Z(z[6])
Z([3,'width:620rpx;margin-top:30rpx;position:relative;'])
Z(z[3])
Z(z[4])
Z(z[6])
Z([[4],[[5],[[4],[[5],[[5],[1,'^input']],[[4],[[5],[[4],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'']],[1,'ticketList']],[1,'$event']],[[4],[[5]]]]]]]]]]]]])
Z([[9],[[9],[[9],[[9],[[9],[[8],'autoplay',[1,false]],[[8],'slidesPerView',[1,'auto']]],[[8],'initialSlide',[1,0]]],[[8],'loop',[1,false]]],[[8],'centeredSlides',[1,true]]],[[8],'spaceBetween',[1,8]]])
Z([[7],[3,'ticketList']])
Z([3,'eac12ac4-2'])
Z([[4],[[5],[1,'default']]])
Z([3,'index'])
Z([3,'item'])
Z(z[91])
Z(z[94])
Z(z[3])
Z(z[6])
Z([[8],'width',[1,'380rpx']])
Z([[2,'+'],[[2,'+'],[[2,'+'],[1,'eac12ac4-3-'],[[7],[3,'index']]],[1,',']],[1,'eac12ac4-2']])
Z(z[93])
Z([3,'seatAndPrice data-v-cf130fde'])
Z([[6],[[7],[3,'item']],[3,'registerName']])
Z([3,'holderName data-v-cf130fde'])
Z([a,[[6],[[7],[3,'item']],[3,'registerName']]])
Z([[7],[3,'buyerName']])
Z(z[105])
Z([a,[[7],[3,'buyerName']]])
Z([[2,'=='],[[6],[[7],[3,'item']],[3,'seatSnapshot']],[1,'无座位']])
Z(z[6])
Z([a,[[2,'+'],[[2,'+'],[1,'无座位(¥'],[[2,'/'],[[6],[[7],[3,'item']],[3,'price']],[1,100]]],[1,')']]])
Z([[6],[[7],[3,'item']],[3,'seatSnapshot']])
Z(z[6])
Z([a,[[2,'+'],[[2,'+'],[[2,'+'],[[2,'+'],[1,''],[[6],[[7],[3,'item']],[3,'seatSnapshot']]],[1,'(¥']],[[2,'/'],[[6],[[7],[3,'item']],[3,'price']],[1,100]]],[1,')']]])
Z(z[6])
Z([a,[[2,'+'],[1,'¥'],[[2,'/'],[[6],[[7],[3,'item']],[3,'price']],[1,100]]]])
Z([3,'seatNo data-v-cf130fde'])
Z([3,'nbsp'])
Z([a,[[2,'+'],[1,'T.N:  '],[[6],[[7],[3,'item']],[3,'documentCode']]]])
Z([3,'swiperShadowHead data-v-cf130fde'])
Z([3,'swiperShadowFoot data-v-cf130fde'])
Z(z[6])
Z(z[47])
Z([[6],[[7],[3,'$root']],[3,'m8']])
Z(z[49])
Z([3,'ticketBottom data-v-cf130fde'])
Z(z[4])
Z([3,'toOrderDetail data-v-cf130fde'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[1,'showQpd']]]]]]]]])
Z([3,'orderDetailTitle data-v-cf130fde'])
Z([3,'查看取票点'])
Z(z[6])
Z([3,'display:flex;align-items:center;'])
Z(z[6])
Z([3,'font-size:24rpx;line-height:36rpx;color:#666666;'])
Z([3,'查看'])
Z(z[6])
Z([[6],[[7],[3,'$root']],[3,'m9']])
Z([3,'width:24rpx;height:24rpx;'])
Z(z[6])
Z([3,'margin-top:8rpx;color:#999999;font-size:22rpx;'])
Z([3,'在取票点出示二维码，即可全部取出'])
Z([3,'soildLine data-v-cf130fde'])
Z(z[4])
Z(z[129])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'jumpOrderDetail']],[[4],[[5],[1,'$0']]]],[[4],[[5],[[2,'+'],[[2,'+'],[1,'ticketIds.'],[[7],[3,'eleTicketIndex']]],[1,'.id']]]]]]]]]]]])
Z([3,'margin-top:24rpx;'])
Z(z[131])
Z([3,'订单详情'])
Z(z[6])
Z(z[134])
Z(z[6])
Z(z[136])
Z(z[137])
Z(z[6])
Z([[6],[[7],[3,'$root']],[3,'m10']])
Z(z[140])
Z(z[144])
Z(z[6])
Z([3,'display:flex;align-items:center;margin-top:20rpx;'])
Z(z[6])
Z([[6],[[7],[3,'$root']],[3,'m11']])
Z([3,'width:32rpx;height:32rpx;'])
Z(z[6])
Z([3,'font-size:28rpx;line-height:40rpx;color:#1A1A1A;margin-left:8rpx;font-weight:bold;'])
Z([3,'温馨提示'])
Z([3,'bottomTip data-v-cf130fde'])
Z([3,'1、活动各资源需要提前采购，'])
Z(z[6])
Z([3,'color:#EA0000;'])
Z([3,'一经售出，不接受退款'])
Z([3,'。\n2、入场时，请参考购票须知或其他备注，参考入场。'])
Z(z[6])
Z([[6],[[7],[3,'$root']],[3,'m12']])
Z(z[49])
Z(z[3])
Z([3,'data-v-cf130fde vue-ref'])
Z([3,'popupqpaddress'])
Z([3,'bottom'])
Z([3,'eac12ac4-4'])
Z(z[93])
Z([3,'content-pop data-v-cf130fde'])
Z([[7],[3,'addressAar']])
Z(z[3])
Z(z[4])
Z(z[6])
Z([[4],[[5],[[4],[[5],[[5],[1,'^closeQPAddress']],[[4],[[5],[[4],[[5],[1,'closeQPAddress']]]]]]]]])
Z([[2,'+'],[[2,'+'],[1,'eac12ac4-5'],[1,',']],[1,'eac12ac4-4']])
Z(z[3])
Z(z[178])
Z([3,'confirm'])
Z([3,'eac12ac4-6'])
Z(z[3])
Z(z[178])
Z([3,'verifycode'])
Z([3,'eac12ac4-7'])
})(__WXML_GLOBAL__.ops_cached.$gwx4_XC_6_1);return __WXML_GLOBAL__.ops_cached.$gwx4_XC_6_1
}
__WXML_GLOBAL__.ops_set.$gwx4_XC_6=z;
__WXML_GLOBAL__.ops_init.$gwx4_XC_6=true;
var x=['./pages_wallet/wallet/ticketCodeEvent.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx4_XC_6_1()
var h5L=_n('view')
_rz(z,h5L,'class',0,e,s,gg)
var o6L=_v()
_(h5L,o6L)
if(_oz(z,1,e,s,gg)){o6L.wxVkey=1
var c7L=_mz(z,'uni-nav-bar',['backgroundColor',2,'bind:__l',1,'bind:clickLeft',2,'border',3,'class',4,'color',5,'data-event-opts',6,'fixed',7,'leftIcon',8,'statusBar',9,'title',10,'vueId',11],[],e,s,gg)
_(o6L,c7L)
}
var o8L=_n('view')
_rz(z,o8L,'class',14,e,s,gg)
var l9L=_mz(z,'image',['class',15,'style',1],[],e,s,gg)
_(o8L,l9L)
var a0L=_n('view')
_rz(z,a0L,'class',17,e,s,gg)
_(o8L,a0L)
var tAM=_mz(z,'image',['class',18,'src',1],[],e,s,gg)
_(o8L,tAM)
_(h5L,o8L)
var eBM=_n('view')
_rz(z,eBM,'class',20,e,s,gg)
var bCM=_mz(z,'view',['bindtap',21,'class',1,'data-event-opts',2],[],e,s,gg)
var oDM=_mz(z,'view',['class',24,'style',1],[],e,s,gg)
var xEM=_n('text')
_rz(z,xEM,'class',26,e,s,gg)
var oFM=_oz(z,27,e,s,gg)
_(xEM,oFM)
_(oDM,xEM)
var fGM=_mz(z,'image',['class',28,'src',1],[],e,s,gg)
_(oDM,fGM)
_(bCM,oDM)
_(eBM,bCM)
var cHM=_n('view')
_rz(z,cHM,'class',30,e,s,gg)
var hIM=_n('view')
_rz(z,hIM,'class',31,e,s,gg)
var oJM=_mz(z,'view',['class',32,'style',1],[],e,s,gg)
_(hIM,oJM)
var cKM=_n('view')
_rz(z,cKM,'class',34,e,s,gg)
var oLM=_n('view')
_rz(z,oLM,'class',35,e,s,gg)
var lMM=_n('text')
_rz(z,lMM,'class',36,e,s,gg)
var aNM=_oz(z,37,e,s,gg)
_(lMM,aNM)
_(oLM,lMM)
var tOM=_mz(z,'text',['class',38,'style',1],[],e,s,gg)
var ePM=_oz(z,40,e,s,gg)
_(tOM,ePM)
_(oLM,tOM)
var bQM=_mz(z,'text',['class',41,'style',1],[],e,s,gg)
var oRM=_oz(z,43,e,s,gg)
_(bQM,oRM)
_(oLM,bQM)
_(cKM,oLM)
var xSM=_mz(z,'image',['class',44,'src',1],[],e,s,gg)
_(cKM,xSM)
_(hIM,cKM)
_(cHM,hIM)
var oTM=_mz(z,'image',['class',46,'mode',1,'src',2,'style',3],[],e,s,gg)
_(cHM,oTM)
var fUM=_n('view')
_rz(z,fUM,'class',50,e,s,gg)
var cVM=_n('text')
_rz(z,cVM,'class',51,e,s,gg)
var hWM=_oz(z,52,e,s,gg)
_(cVM,hWM)
_(fUM,cVM)
var oXM=_n('view')
_rz(z,oXM,'class',53,e,s,gg)
var cYM=_n('text')
_rz(z,cYM,'class',54,e,s,gg)
var oZM=_oz(z,55,e,s,gg)
_(cYM,oZM)
_(oXM,cYM)
var l1M=_n('text')
_rz(z,l1M,'class',56,e,s,gg)
var a2M=_oz(z,57,e,s,gg)
_(l1M,a2M)
_(oXM,l1M)
var t3M=_n('view')
_rz(z,t3M,'class',58,e,s,gg)
var e4M=_mz(z,'image',['bindtap',59,'class',1,'data-event-opts',2,'src',3],[],e,s,gg)
_(t3M,e4M)
var b5M=_n('view')
_rz(z,b5M,'class',63,e,s,gg)
var x7M=_n('view')
_rz(z,x7M,'class',64,e,s,gg)
var o8M=_oz(z,65,e,s,gg)
_(x7M,o8M)
_(b5M,x7M)
var f9M=_mz(z,'image',['class',66,'src',1,'style',2],[],e,s,gg)
_(b5M,f9M)
var o6M=_v()
_(b5M,o6M)
if(_oz(z,69,e,s,gg)){o6M.wxVkey=1
var c0M=_n('view')
_rz(z,c0M,'class',70,e,s,gg)
var hAN=_v()
_(c0M,hAN)
if(_oz(z,71,e,s,gg)){hAN.wxVkey=1
var oBN=_mz(z,'image',['class',72,'src',1],[],e,s,gg)
_(hAN,oBN)
}
else{hAN.wxVkey=2
var cCN=_v()
_(hAN,cCN)
if(_oz(z,74,e,s,gg)){cCN.wxVkey=1
var oDN=_mz(z,'image',['class',75,'src',1],[],e,s,gg)
_(cCN,oDN)
}
else{cCN.wxVkey=2
var lEN=_v()
_(cCN,lEN)
if(_oz(z,77,e,s,gg)){lEN.wxVkey=1
var aFN=_mz(z,'image',['class',78,'src',1],[],e,s,gg)
_(lEN,aFN)
}
lEN.wxXCkey=1
}
cCN.wxXCkey=1
}
hAN.wxXCkey=1
_(o6M,c0M)
}
o6M.wxXCkey=1
_(t3M,b5M)
var tGN=_mz(z,'image',['bindtap',80,'class',1,'data-event-opts',2,'src',3],[],e,s,gg)
_(t3M,tGN)
_(oXM,t3M)
var eHN=_mz(z,'view',['class',84,'style',1],[],e,s,gg)
var bIN=_mz(z,'z-swiper',['bind:__l',86,'bind:input',1,'class',2,'data-event-opts',3,'options',4,'value',5,'vueId',6,'vueSlots',7],[],e,s,gg)
var oJN=_v()
_(bIN,oJN)
var xKN=function(fMN,oLN,cNN,gg){
var oPN=_mz(z,'z-swiper-item',['bind:__l',98,'class',1,'customStyle',2,'vueId',3,'vueSlots',4],[],fMN,oLN,gg)
var cQN=_n('view')
_rz(z,cQN,'class',103,fMN,oLN,gg)
var oRN=_v()
_(cQN,oRN)
if(_oz(z,104,fMN,oLN,gg)){oRN.wxVkey=1
var aTN=_n('text')
_rz(z,aTN,'class',105,fMN,oLN,gg)
var tUN=_oz(z,106,fMN,oLN,gg)
_(aTN,tUN)
_(oRN,aTN)
}
else{oRN.wxVkey=2
var eVN=_v()
_(oRN,eVN)
if(_oz(z,107,fMN,oLN,gg)){eVN.wxVkey=1
var bWN=_n('text')
_rz(z,bWN,'class',108,fMN,oLN,gg)
var oXN=_oz(z,109,fMN,oLN,gg)
_(bWN,oXN)
_(eVN,bWN)
}
eVN.wxXCkey=1
}
var lSN=_v()
_(cQN,lSN)
if(_oz(z,110,fMN,oLN,gg)){lSN.wxVkey=1
var xYN=_n('view')
_rz(z,xYN,'class',111,fMN,oLN,gg)
var oZN=_oz(z,112,fMN,oLN,gg)
_(xYN,oZN)
_(lSN,xYN)
}
else{lSN.wxVkey=2
var f1N=_v()
_(lSN,f1N)
if(_oz(z,113,fMN,oLN,gg)){f1N.wxVkey=1
var c2N=_n('view')
_rz(z,c2N,'class',114,fMN,oLN,gg)
var h3N=_oz(z,115,fMN,oLN,gg)
_(c2N,h3N)
_(f1N,c2N)
}
else{f1N.wxVkey=2
var o4N=_n('view')
_rz(z,o4N,'class',116,fMN,oLN,gg)
var c5N=_oz(z,117,fMN,oLN,gg)
_(o4N,c5N)
_(f1N,o4N)
}
f1N.wxXCkey=1
}
var o6N=_mz(z,'text',['class',118,'space',1],[],fMN,oLN,gg)
var l7N=_oz(z,120,fMN,oLN,gg)
_(o6N,l7N)
_(cQN,o6N)
oRN.wxXCkey=1
lSN.wxXCkey=1
_(oPN,cQN)
_(cNN,oPN)
return cNN
}
oJN.wxXCkey=4
_2z(z,96,xKN,e,s,gg,oJN,'item','index','index')
_(eHN,bIN)
var a8N=_n('view')
_rz(z,a8N,'class',121,e,s,gg)
_(eHN,a8N)
var t9N=_n('view')
_rz(z,t9N,'class',122,e,s,gg)
_(eHN,t9N)
_(oXM,eHN)
_(fUM,oXM)
_(cHM,fUM)
var e0N=_mz(z,'image',['class',123,'mode',1,'src',2,'style',3],[],e,s,gg)
_(cHM,e0N)
var bAO=_n('view')
_rz(z,bAO,'class',127,e,s,gg)
var oBO=_mz(z,'view',['bindtap',128,'class',1,'data-event-opts',2],[],e,s,gg)
var xCO=_n('text')
_rz(z,xCO,'class',131,e,s,gg)
var oDO=_oz(z,132,e,s,gg)
_(xCO,oDO)
_(oBO,xCO)
var fEO=_mz(z,'view',['class',133,'style',1],[],e,s,gg)
var cFO=_mz(z,'text',['class',135,'style',1],[],e,s,gg)
var hGO=_oz(z,137,e,s,gg)
_(cFO,hGO)
_(fEO,cFO)
var oHO=_mz(z,'image',['class',138,'src',1,'style',2],[],e,s,gg)
_(fEO,oHO)
_(oBO,fEO)
_(bAO,oBO)
var cIO=_mz(z,'text',['class',141,'style',1],[],e,s,gg)
var oJO=_oz(z,143,e,s,gg)
_(cIO,oJO)
_(bAO,cIO)
var lKO=_n('view')
_rz(z,lKO,'class',144,e,s,gg)
_(bAO,lKO)
var aLO=_mz(z,'view',['bindtap',145,'class',1,'data-event-opts',2,'style',3],[],e,s,gg)
var tMO=_n('text')
_rz(z,tMO,'class',149,e,s,gg)
var eNO=_oz(z,150,e,s,gg)
_(tMO,eNO)
_(aLO,tMO)
var bOO=_mz(z,'view',['class',151,'style',1],[],e,s,gg)
var oPO=_mz(z,'text',['class',153,'style',1],[],e,s,gg)
var xQO=_oz(z,155,e,s,gg)
_(oPO,xQO)
_(bOO,oPO)
var oRO=_mz(z,'image',['class',156,'src',1,'style',2],[],e,s,gg)
_(bOO,oRO)
_(aLO,bOO)
_(bAO,aLO)
var fSO=_n('view')
_rz(z,fSO,'class',159,e,s,gg)
_(bAO,fSO)
var cTO=_mz(z,'view',['class',160,'style',1],[],e,s,gg)
var hUO=_mz(z,'image',['class',162,'src',1,'style',2],[],e,s,gg)
_(cTO,hUO)
var oVO=_mz(z,'text',['class',165,'style',1],[],e,s,gg)
var cWO=_oz(z,167,e,s,gg)
_(oVO,cWO)
_(cTO,oVO)
_(bAO,cTO)
var oXO=_n('text')
_rz(z,oXO,'class',168,e,s,gg)
var lYO=_oz(z,169,e,s,gg)
_(oXO,lYO)
var aZO=_mz(z,'text',['class',170,'style',1],[],e,s,gg)
var t1O=_oz(z,172,e,s,gg)
_(aZO,t1O)
_(oXO,aZO)
var e2O=_oz(z,173,e,s,gg)
_(oXO,e2O)
_(bAO,oXO)
_(cHM,bAO)
var b3O=_mz(z,'image',['class',174,'src',1,'style',2],[],e,s,gg)
_(cHM,b3O)
_(eBM,cHM)
_(h5L,eBM)
var o4O=_mz(z,'uni-popup',['bind:__l',177,'class',1,'data-ref',2,'type',3,'vueId',4,'vueSlots',5],[],e,s,gg)
var x5O=_n('view')
_rz(z,x5O,'class',183,e,s,gg)
var o6O=_mz(z,'ticketaddress',['addressAar',184,'bind:__l',1,'bind:closeQPAddress',2,'class',3,'data-event-opts',4,'vueId',5],[],e,s,gg)
_(x5O,o6O)
_(o4O,x5O)
_(h5L,o4O)
var f7O=_mz(z,'pup-limit',['bind:__l',190,'class',1,'data-ref',2,'vueId',3],[],e,s,gg)
_(h5L,f7O)
var c8O=_mz(z,'verify-code-popup',['bind:__l',194,'class',1,'data-ref',2,'vueId',3],[],e,s,gg)
_(h5L,c8O)
o6L.wxXCkey=1
o6L.wxXCkey=3
_(r,h5L)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx4_XC_6";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx4_XC_6();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages_wallet/wallet/ticketCodeEvent.wxml'] = [$gwx4_XC_6, './pages_wallet/wallet/ticketCodeEvent.wxml'];else __wxAppCode__['pages_wallet/wallet/ticketCodeEvent.wxml'] = $gwx4_XC_6( './pages_wallet/wallet/ticketCodeEvent.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages_wallet/wallet/ticketCodeEvent.wxss'] = setCssToHead([".",[1],"contentdetail.",[1],"data-v-cf130fde{display:flex;flex-direction:column;height:100vh;justify-content:center}\n.",[1],"contentdetail .",[1],"mainBg.",[1],"data-v-cf130fde{height:100vh;left:0;overflow:hidden;position:fixed;top:0;width:100%}\n.",[1],"contentdetail .",[1],"mainBg .",[1],"topBlurImage.",[1],"data-v-cf130fde{background:var(--bgurl);background-size:100% 100%;height:100%;position:absolute;width:100%}\n.",[1],"contentdetail .",[1],"mainBg .",[1],"topBlurBlack.",[1],"data-v-cf130fde{background-color:#000;background-size:100% 100%;height:100%;opacity:.6;position:absolute;width:100%}\n.",[1],"contentdetail .",[1],"mainBg .",[1],"topBlackForeground.",[1],"data-v-cf130fde{-webkit-backdrop-filter:blur(100px);backdrop-filter:blur(100px);height:100%;position:absolute;width:100%}\n.",[1],"contentdetail .",[1],"mainContent.",[1],"data-v-cf130fde{flex:1;margin-top:",[0,30],";overflow-y:auto;padding-left:",[0,40],";padding-right:",[0,40],";z-index:2}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"topLocation.",[1],"data-v-cf130fde{background-image:url(https://res.dasheng.top/app/icon/wallet_detail_locatoin_bg.png);background-repeat:no-repeat;background-size:100% 100%;height:",[0,112],";width:100%}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"topLocation .",[1],"locationName.",[1],"data-v-cf130fde{-webkit-line-clamp:1;-webkit-box-orient:vertical;color:#1a1a1a;display:-webkit-box;flex:1;font-size:",[0,28],";line-height:",[0,36],";margin-left:",[0,36],";margin-right:",[0,10],";overflow:hidden;text-overflow:ellipsis}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"topLocation wx-image.",[1],"data-v-cf130fde{height:",[0,40],";margin-right:",[0,64],";width:",[0,40],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent.",[1],"data-v-cf130fde{background-repeat:no-repeat;display:flex;flex-direction:column;margin-top:",[0,-32],";width:100%}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketTop.",[1],"data-v-cf130fde{background-color:#fff;border-top-left-radius:",[0,24],";border-top-right-radius:",[0,24],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketTop .",[1],"ticketTopContent.",[1],"data-v-cf130fde{display:flex;height:",[0,162],";width:100%}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketTop .",[1],"ticketTopContent .",[1],"ticketDetail.",[1],"data-v-cf130fde{display:flex;flex:1;flex-direction:column;height:",[0,162],";margin-left:",[0,32],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketTop .",[1],"ticketTopContent .",[1],"ticketDetail .",[1],"tName.",[1],"data-v-cf130fde{-webkit-line-clamp:2;-webkit-box-orient:vertical;color:#1a1a1a;display:-webkit-box;font-size:",[0,28],";font-weight:700;height:",[0,80],";line-height:",[0,40],";overflow:hidden;text-overflow:ellipsis}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketTop .",[1],"ticketTopContent .",[1],"ticketDetail .",[1],"tTime.",[1],"data-v-cf130fde{-webkit-line-clamp:1;-webkit-box-orient:vertical;color:#999;display:-webkit-box;font-size:",[0,24],";line-height:",[0,32],";overflow:hidden;text-overflow:ellipsis}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketTop .",[1],"ticketTopContent .",[1],"ticketImg.",[1],"data-v-cf130fde{border-radius:",[0,8],";height:",[0,148],";margin-left:",[0,32],";margin-right:",[0,32],";width:",[0,112],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle.",[1],"data-v-cf130fde{background-color:#fff;padding-left:",[0,32],";padding-right:",[0,32],";position:relative}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketIndex.",[1],"data-v-cf130fde{color:#1a1a1a;font-size:",[0,28],";left:",[0,36],";line-height:",[0,40],";position:absolute;top:",[0,0],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent.",[1],"data-v-cf130fde{align-items:center;display:flex;flex-direction:column}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"sessionsName.",[1],"data-v-cf130fde{color:#1a1a1a;font-size:",[0,28],";font-weight:700;line-height:",[0,40],";margin:",[0,8]," ",[0,70]," ",[0,0],";text-align:center}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"sessionsTime.",[1],"data-v-cf130fde{color:#999;font-size:",[0,24],";line-height:",[0,32],";margin-top:",[0,8],";text-align:center}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent.",[1],"data-v-cf130fde{align-items:center;display:flex;justify-content:space-between;margin-top:",[0,24],";width:100%}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"preCode.",[1],"data-v-cf130fde{height:",[0,64],";margin-bottom:",[0,60],";margin-left:",[0,2],";width:",[0,64],"}\n@-webkit-keyframes rotate-data-v-cf130fde{100%{-webkit-transform:rotate(1turn);transform:rotate(1turn)}\n}@keyframes rotate-data-v-cf130fde{100%{-webkit-transform:rotate(1turn);transform:rotate(1turn)}\n}.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder.",[1],"data-v-cf130fde{align-items:center;background:#fff;border:",[0,2]," solid #eee;border-radius:",[0,16],";box-sizing:border-box;display:flex;flex-direction:column;height:",[0,416],";justify-content:center;margin:0 auto;overflow:hidden;padding:",[0,5],";position:relative;width:",[0,422],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder .",[1],"ticketCode.",[1],"data-v-cf130fde{align-items:center;background:#f5f6fa;border-radius:",[0,8],";color:#1a1a1a;display:flex;font-size:",[0,28],";font-weight:700;height:",[0,60],";justify-content:center;padding-left:",[0,24],";padding-right:",[0,24],";z-index:5}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder.",[1],"data-v-cf130fde::after{-webkit-animation:rotate-data-v-cf130fde 4s linear infinite;animation:rotate-data-v-cf130fde 4s linear infinite;background-image:conic-gradient(hsla(0,0%,100%,0) 1%,rgba(250,100,250,.2) 10%,#8bf1f9 15%,#6ff7b5 15%,hsla(0,0%,100%,0) 1%);border-radius:",[0,10],";content:\x22\x22;height:300%;left:-100%;overflow:hidden;position:absolute;top:-100%;width:300%;z-index:1}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder.",[1],"data-v-cf130fde::before{background:#fff;border-radius:",[0,10],";content:\x22\x22;height:calc(100% - ",[0,12],");position:absolute;width:calc(100% - ",[0,12],");z-index:2}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder .",[1],"idcardPlaceHolder.",[1],"data-v-cf130fde{height:",[0,196],";width:",[0,302],";z-index:5}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"qrCodeBorder .",[1],"warnImage.",[1],"data-v-cf130fde{bottom:0;height:",[0,168],";left:0;margin-bottom:",[0,86],";margin-left:",[0,120],";position:absolute;width:",[0,168],";z-index:5}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"qrCodeContent .",[1],"nextCode.",[1],"data-v-cf130fde{height:",[0,64],";margin-bottom:",[0,60],";margin-right:",[0,2],";width:",[0,64],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"checknum.",[1],"data-v-cf130fde{align-items:center;background-size:100% 100%;color:#fff;display:flex;font-size:",[0,24],";font-weight:700;height:",[0,60],";justify-content:center;margin-top:",[0,-30],";padding-top:",[0,6],";text-align:center;width:",[0,378],";z-index:99}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"swiperShadowHead.",[1],"data-v-cf130fde{background:linear-gradient(90deg,#fff 50%,hsla(0,0%,100%,0));height:100%;left:0;position:absolute;top:0;width:",[0,54],";z-index:2}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"swiperShadowFoot.",[1],"data-v-cf130fde{background:linear-gradient(270deg,#fff 60%,hsla(0,0%,100%,0));height:100%;position:absolute;right:0;top:0;width:",[0,54],";z-index:2}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"holderName.",[1],"data-v-cf130fde{color:#1a1a1a;font-size:",[0,28],";font-weight:700;line-height:",[0,40],";margin:",[0,16],";text-align:center}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"seatAndPrice.",[1],"data-v-cf130fde{align-items:center;background:#f5f6fa;border:",[0,2]," solid rgba(236,239,247,0);border-radius:",[0,8],";color:#999;display:flex;flex-direction:column;font-size:",[0,24],";justify-content:center;line-height:",[0,40],";text-align:center;width:100%}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketMiddle .",[1],"ticketMiddleContent .",[1],"seatNo.",[1],"data-v-cf130fde{border:1px solid #d8d8d8;border-radius:",[0,36],";color:#999;font-size:",[0,20],";height:",[0,36],";line-height:",[0,36],";margin:",[0,16],";padding-left:",[0,12],";padding-right:",[0,12],";text-align:center}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketBottom.",[1],"data-v-cf130fde{background-color:#fff;margin-top:",[0,-1],";padding:",[0,0]," ",[0,32],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketBottom .",[1],"toOrderDetail.",[1],"data-v-cf130fde{align-items:center;display:flex;justify-content:space-between}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketBottom .",[1],"toOrderDetail .",[1],"orderDetailTitle.",[1],"data-v-cf130fde{color:#1a1a1a;font-size:",[0,28],";font-weight:700;line-height:",[0,40],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"ticketBottom .",[1],"bottomTip.",[1],"data-v-cf130fde{color:#666;font-size:",[0,24],";line-height:",[0,40],";margin-top:",[0,8],"}\n.",[1],"contentdetail .",[1],"mainContent .",[1],"ticketContent .",[1],"soildLine.",[1],"data-v-cf130fde{background-color:#eee;height:",[0,1],";margin-top:",[0,24],"}\n.",[1],"contentdetail .",[1],"classgrouped.",[1],"data-v-cf130fde{opacity:.5}\n.",[1],"contentdetail .",[1],"content-pop.",[1],"data-v-cf130fde{border-radius:",[0,25]," ",[0,25]," 0 0;width:100vw}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages_wallet/wallet/ticketCodeEvent.wxss:1:1337)",{path:"./pages_wallet/wallet/ticketCodeEvent.wxss"});
}